all:
	gcc -o ex1a ex1a.c Arquivos/abbLista.c
	gcc -o ex1b ex1b.c Arquivos/abbLista.c
	gcc -o ex1c ex1c.c Arquivos/abbLista.c
	gcc -o ex2 ex2.c Arquivos/abbLista.c
	gcc -o ex3 ex3.c Arquivos/abbLista.c
	gcc -o ex4 ex4.c Arquivos/abbLista.c